### ISSUE TITLE
Relative imports do not work for FHIR-1.8.0 when using Python 2.7.12

### ISSUE THREAD

**Issue by Abildtoft** [smart-on-fhir/client-py#28]
When using either the FHIR-1.8.0 release or the latest-ci feature branch (the latter just to confirm that the issue also exists for FHIR 1.9), the relative imports fails for fhirreference.

The simplest way to reproduce is to create a small Python script in the root of a downloaded version of client-py-FHIR-1.8.0:

```
import isodate
import fhirclient.models.patient as p
```
Using Ubuntu 16.04, "python3 test_importing.py" works without issue (the exact Python version is 3.5.2), while "python2.7 test_importing.py" results in the following:

> Traceback (most recent call last):
>   File "test_importing.py", line 2, in <module>
>     import fhirclient.models.patient as p
>   File "/home/mikkel/Downloads/client-py-FHIR-1.8.0/fhirclient/models/patient.py", line 8, in <module>
>     from . import domainresource
>   File "/home/mikkel/Downloads/client-py-FHIR-1.8.0/fhirclient/models/domainresource.py", line 55, in <module>
>     from . import extension
>   File "/home/mikkel/Downloads/client-py-FHIR-1.8.0/fhirclient/models/extension.py", line 232, in <module>
>     from . import annotation
>   File "/home/mikkel/Downloads/client-py-FHIR-1.8.0/fhirclient/models/annotation.py", line 57, in <module>
>     from . import fhirreference
>   File "/home/mikkel/Downloads/client-py-FHIR-1.8.0/fhirclient/models/fhirreference.py", line 7, in <module>
>     from . import reference
>   File "/home/mikkel/Downloads/client-py-FHIR-1.8.0/fhirclient/models/reference.py", line 48, in <module>
>     from . import identifier
>   File "/home/mikkel/Downloads/client-py-FHIR-1.8.0/fhirclient/models/identifier.py", line 66, in <module>
>     from . import fhirreference
> ImportError: cannot import name fhirreference

The error is not limited to the Patient resource, but can be reproduced when trying to import other FHIR resources (e.g., Task, Questionnaire) that contains references.

The problem does not exist in the FHIR-1.6.0 release, which works with 2.7.12.

Please let me know if I can be of any help when/if you have the time to look at this issue :)

**Comment by Abildtoft** [comment]
The issue appears to be a circular import triggered by the addition of logical references (using identifier) in [FHIR 1.8](http://hl7.org/fhir/2017Jan/references.html), as fhirreference imports reference which imports identifier which imports fhirreference.

While I'm unsure why this circular import doesn't fail in Python 3.5.2, it can be solved for Python 2.7.12 by following the example [here](http://stackoverflow.com/a/33547682). E.g., in identifier.py:
```
try:
    from . import fhirreference
except ImportError:
    import sys
    fhirreference = sys.modules[__package__ + '.fhirreference']
```

And in reference.py:

```
try:
    from . import identifier
except ImportError:
    import sys
    identifier = sys.modules[__package__ + '.identifier']
```

**Comment by p2** [comment]
Thanks. Circular imports seem to be okay since Python 3.5+, I've adopted your solution so the library works with older Python versions as well. 👍🏼
