### ISSUE TITLE
backboneelement ImportError - Python 3.4.2

### ISSUE THREAD

**Issue by dostergaard** [smart-on-fhir/client-py#20]
This may be similar to a problem noted in issue #8

This occurred running flask_app.py after following the build instructions in the README.md

(fcenv)xxxx@raspberrypi:\~/projects/client-py $ python -V
Python 3.4.2
(fcenv)xxxx@raspberrypi:\~/projects/client-py $ python flask_app.py 
Traceback (most recent call last):
  File "flask_app.py", line 5, in <module>
    from fhirclient.models.medication import Medication
  File "/home/xxxx/projects/client-py/fhirclient/models/medication.py", line 8, in <module>
    from . import domainresource
  File "/home/xxxx/projects/client-py/fhirclient/models/domainresource.py", line 55, in <module>
    from . import extension
  File "/home/xxxx/projects/client-py/fhirclient/models/extension.py", line 206, in <module>
    from . import annotation
  File "/home/xxxx/projects/client-py/fhirclient/models/annotation.py", line 57, in <module>
    from . import fhirreference
  File "/home/xxxx/projects/client-py/fhirclient/models/fhirreference.py", line 98, in <module>
    from . import bundle
  File "/home/xxxx/projects/client-py/fhirclient/models/bundle.py", line 61, in <module>
    from . import backboneelement
  File "/home/xxxx/projects/client-py/fhirclient/models/backboneelement.py", line 41, in <module>
    from . import extension
ImportError: cannot import name 'extension'
(fcenv)xxxx@raspberrypi:~/projects/client-py $

**Comment by p2** [comment]
I've just tested latest `master` and it works fine with Python 2.7.10 and 3.5.1. Which branch/version are you on?

**Comment by dostergaard** [comment]
I just cloned the master as follows:
git clone https://github.com/smart-on-fhir/client-py.git
cd client-py
virtualenv -p python3 fcenv3
. fcenv3/bin/activate
pip install -r requirements_flask_app.txt
python flask_app.py

I just tried it again but this time on my Gentoo box running python v3.4.3 with the same results.

Oh, and I agree it works fine using python 2.7.10.

**Comment by allisonbertrandsa** [comment]
I had the same issue on Cygwin after following the build instructions in the README.md, Python 3.4.5.

For me, the following has flask_app.py up and running:
diff --git a/fhirclient/models/backboneelement.py b/fhirclient/models/backboneelement.py
index 70446b9..02ed82a 100644
--- a/fhirclient/models/backboneelement.py
+++ b/fhirclient/models/backboneelement.py
@@ -33,9 +33,9 @@ class BackboneElement(element.Element):
     def elementProperties(self):
         js = super(BackboneElement, self).elementProperties()
         js.extend([
-            ("modifierExtension", "modifierExtension", extension.Extension, True, None, False),
+            ("modifierExtension", "modifierExtension", fhirclient.models.extension.Extension, True, None, False),
         ])
         return js


-from . import extension
+import fhirclient.models.extension
diff --git a/fhirclient/models/signature.py b/fhirclient/models/signature.py
index 59c05a9..f12e251 100644
--- a/fhirclient/models/signature.py
+++ b/fhirclient/models/signature.py
@@ -59,7 +59,7 @@ class Signature(element.Element):
             ("contentType", "contentType", str, False, None, True),
             ("type", "type", coding.Coding, True, None, True),
             ("when", "when", fhirdate.FHIRDate, False, None, True),
-            ("whoReference", "whoReference", fhirreference.FHIRReference, False, "who", True),
+            ("whoReference", "whoReference", fhirclient.models.fhirreference.FHIRReference, False, "who", True),
             ("whoUri", "whoUri", str, False, "who", True),
         ])
         return js
@@ -67,4 +67,4 @@ class Signature(element.Element):

 from . import coding
 from . import fhirdate
-from . import fhirreference
+import fhirclient.models.fhirreference
